# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    container_name: ${COMPOSE_PROJECT_NAME}-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    container_name: ${COMPOSE_PROJECT_NAME}-adminer