# Usa la imagen base de MySQL 5.7
FROM mysql:5.7

# Establece las variables de entorno necesarias
ENV MYSQL_DATABASE='example_database'
ENV MYSQL_USER='user'
ENV MYSQL_PASSWORD='password'
ENV MYSQL_ROOT_PASSWORD='root'

# Expone el puerto 3306
EXPOSE 3306
