# Usa la imagen base de MariaDB
FROM mariadb:latest

# Establece las variables de entorno necesarias
ENV MARIADB_ROOT_PASSWORD='root'
ENV MARIADB_DATABASE='example'
ENV MARIADB_USER='example'
ENV MARIADB_PASSWORD='example'


# Expone el puerto 3306
EXPOSE 3306
